# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_12factor` gem.
# Please instead update this file by running `bin/tapioca gem rails_12factor`.


# source://rails_12factor//lib/rails_12factor.rb#1
module Rails12factor; end
