# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_stdout_logging` gem.
# Please instead update this file by running `bin/tapioca gem rails_stdout_logging`.


# source://rails_stdout_logging//lib/rails_stdout_logging/version.rb#1
module RailsStdoutLogging; end

# source://rails_stdout_logging//lib/rails_stdout_logging/rails.rb#6
class RailsStdoutLogging::Rails
  class << self
    # source://rails_stdout_logging//lib/rails_stdout_logging/rails.rb#7
    def heroku_stdout_logger; end

    # source://rails_stdout_logging//lib/rails_stdout_logging/rails.rb#14
    def log_level; end

    # source://rails_stdout_logging//lib/rails_stdout_logging/rails.rb#18
    def set_logger; end
  end
end

# source://rails_stdout_logging//lib/rails_stdout_logging/rails3.rb#4
class RailsStdoutLogging::Rails3 < ::RailsStdoutLogging::Rails
  class << self
    # source://rails_stdout_logging//lib/rails_stdout_logging/rails3.rb#5
    def set_logger(config); end
  end
end

# source://rails_stdout_logging//lib/rails_stdout_logging/railtie.rb#4
class RailsStdoutLogging::Railtie < ::Rails::Railtie; end

# source://rails_stdout_logging//lib/rails_stdout_logging/rails.rb#2
class RailsStdoutLogging::StdoutLogger < ::ActiveSupport::Logger; end

# source://rails_stdout_logging//lib/rails_stdout_logging/version.rb#2
RailsStdoutLogging::VERSION = T.let(T.unsafe(nil), String)
