# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_serve_static_assets` gem.
# Please instead update this file by running `bin/tapioca gem rails_serve_static_assets`.


# source://rails_serve_static_assets//lib/rails_serve_static_assets/version.rb#1
module RailsServeStaticAssets; end

# source://rails_serve_static_assets//lib/rails_serve_static_assets/railtie.rb#2
class RailsServeStaticAssets::Railtie < ::Rails::Railtie; end

# source://rails_serve_static_assets//lib/rails_serve_static_assets/version.rb#2
RailsServeStaticAssets::VERSION = T.let(T.unsafe(nil), String)
