# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rollbar` gem.
# Please instead update this file by running `bin/tapioca gem rollbar`.


module ActiveModel::Validations
  include ::Rollbar::ActiveRecordExtension
end

# The Rollbar module. It stores a Rollbar::Notifier per thread and
# provides some module methods in order to use the current thread notifier.
#
# source://rollbar//lib/rollbar/version.rb#1
module Rollbar
  class << self
    # Clears the current thread notifier and the root notifier.
    # In the practice this should be used only on the specs
    #
    # source://rollbar//lib/rollbar.rb#119
    def clear_notifier!; end

    # Returns the configuration for the current notifier.
    # The current notifier is Rollbar.notifier and exists
    # one per thread.
    #
    # source://rollbar//lib/rollbar.rb#84
    def configuration; end

    # Configures the root notifier and loads the plugins
    #
    # source://rollbar//lib/rollbar.rb#65
    def configure(&block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def critical(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def debug(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def error(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def info(*args, **_arg1, &block); end

    # source://rollbar//lib/rollbar.rb#96
    def last_report; end

    # source://rollbar//lib/rollbar.rb#100
    def last_report=(report); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def log(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def log_debug(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def log_error(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def log_info(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def log_warning(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def logger(*args, **_arg1, &block); end

    # source://rollbar//lib/rollbar.rb#37
    def notifier; end

    # source://rollbar//lib/rollbar.rb#43
    def notifier=(notifier); end

    # source://rollbar//lib/rollbar.rb#92
    def plugins; end

    # Sets the attribute plugins
    #
    # @param value the value to set the attribute plugins to.
    #
    # source://rollbar//lib/rollbar.rb#35
    def plugins=(_arg0); end

    # source://rollbar//lib/rollbar.rb#60
    def preconfigure(&block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def process_from_async_handler(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def process_item(*args, **_arg1, &block); end

    # Reconfigures the root notifier
    #
    # source://rollbar//lib/rollbar.rb#72
    def reconfigure(&block); end

    # Backwards compatibility methods
    #
    # source://rollbar//lib/rollbar.rb#163
    def report_exception(exception, request_data = T.unsafe(nil), person_data = T.unsafe(nil), level = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar.rb#177
    def report_message(message, level = T.unsafe(nil), extra_data = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar.rb#184
    def report_message_with_request(message, level = T.unsafe(nil), request_data = T.unsafe(nil), person_data = T.unsafe(nil), extra_data = T.unsafe(nil)); end

    # Resets the scope for the current thread notifier. The notifier
    # reference is kept so we reuse the notifier.
    # This is a change from version 2.13.0. Before this version
    # this method clears the notifier.
    #
    # It was used in order to reset the scope and reusing the global
    # configuration Rollbar.configuration. Since now Rollbar.configuration
    # points to the current notifier configuration, we can resue the
    # notifier instance and just reset the scope.
    #
    # source://rollbar//lib/rollbar.rb#113
    def reset_notifier!; end

    # It's the first notifier instantiated in the
    # process. We store it so all the next per-thread
    # notifiers can inherit its configuration
    # The methods Rollbar.configure, Rollbar.reconfigure,
    # Rollbar.preconfigure and Rollbar.unconfigure work
    # on this notifier.
    # Before v2.13.0 these methods worked on the global
    # configuration, so in the practice the behavior is the same,
    # since they work on the root notifier's configuration
    #
    # source://rollbar//lib/rollbar.rb#56
    def root_notifier; end

    # Sets the attribute root_notifier
    #
    # @param value the value to set the attribute root_notifier to.
    #
    # source://rollbar//lib/rollbar.rb#35
    def root_notifier=(_arg0); end

    # @return [Boolean]
    #
    # source://rollbar//lib/rollbar.rb#88
    def safely?; end

    # source://forwardable/1.3.2/forwardable.rb#229
    def scope(*args, **_arg1, &block); end

    # source://rollbar//lib/rollbar.rb#157
    def scope!(options = T.unsafe(nil)); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def scope_object(*args, **_arg1, &block); end

    # Create a new Notifier instance using the received options and
    # set it as the current thread notifier.
    # The calls to Rollbar inside the received block will use then this
    # new Notifier object.
    #
    # @example
    #
    #   new_scope = { job_type: 'scheduled' }
    #   new_config = { use_async: false }
    #
    #   Rollbar.scoped(new_scope, new_config) do
    #   begin
    #   # do stuff
    #   rescue => e
    #   Rollbar.error(e)
    #   end
    #   end
    #
    # source://rollbar//lib/rollbar.rb#141
    def scoped(options = T.unsafe(nil), config_overrides = T.unsafe(nil)); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def send_failsafe(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def silenced(*args, **_arg1, &block); end

    # Unconfigures the root notifier
    #
    # source://rollbar//lib/rollbar.rb#77
    def unconfigure; end

    # source://forwardable/1.3.2/forwardable.rb#229
    def warn(*args, **_arg1, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def warning(*args, **_arg1, &block); end

    # Create a new Notifier instance with a new configuration
    # using the current one but merging the passed options.
    #
    # source://rollbar//lib/rollbar.rb#153
    def with_config(overrides, &block); end
  end
end

# Report any uncaught errors in a job to Rollbar and reraise
#
# source://rollbar//lib/rollbar/plugins/active_job.rb#3
module Rollbar::ActiveJob
  class << self
    # @private
    #
    # source://rollbar//lib/rollbar/plugins/active_job.rb#4
    def included(base); end
  end
end

# source://rollbar//lib/rollbar/plugins/validations.rb#17
module Rollbar::ActiveRecordExtension
  # source://rollbar//lib/rollbar/plugins/validations.rb#18
  def report_validation_errors_to_rollbar; end
end

# source://rollbar//lib/rollbar/configuration.rb#4
class Rollbar::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://rollbar//lib/rollbar/configuration.rb#92
  def initialize; end

  # allow params to be read like a hash
  #
  # source://rollbar//lib/rollbar/configuration.rb#357
  def [](option); end

  # Returns the value of attribute access_token.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def access_token; end

  # Sets the attribute access_token
  #
  # @param value the value to set the attribute access_token to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def access_token=(_arg0); end

  # Returns the value of attribute anonymize_user_ip.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def anonymize_user_ip; end

  # Sets the attribute anonymize_user_ip
  #
  # @param value the value to set the attribute anonymize_user_ip to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def anonymize_user_ip=(_arg0); end

  # Returns the value of attribute async_handler.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_handler; end

  # Sets the attribute async_handler
  #
  # @param value the value to set the attribute async_handler to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_handler=(_arg0); end

  # Returns the value of attribute async_json_payload.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_json_payload; end

  # Sets the attribute async_json_payload
  #
  # @param value the value to set the attribute async_json_payload to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_json_payload=(_arg0); end

  # Returns the value of attribute async_skip_report_handler.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_skip_report_handler; end

  # Sets the attribute async_skip_report_handler
  #
  # @param value the value to set the attribute async_skip_report_handler to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def async_skip_report_handler=(_arg0); end

  # Returns the value of attribute backtrace_cleaner.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def backtrace_cleaner; end

  # Sets the attribute backtrace_cleaner
  #
  # @param value the value to set the attribute backtrace_cleaner to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def backtrace_cleaner=(_arg0); end

  # Returns the value of attribute before_process.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def before_process; end

  # source://rollbar//lib/rollbar/configuration.rb#322
  def before_process=(*handler); end

  # Returns the value of attribute branch.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def branch; end

  # Sets the attribute branch
  #
  # @param value the value to set the attribute branch to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def branch=(_arg0); end

  # Returns the value of attribute capture_uncaught.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def capture_uncaught; end

  # Sets the attribute capture_uncaught
  #
  # @param value the value to set the attribute capture_uncaught to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def capture_uncaught=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#199
  def clone; end

  # Returns the value of attribute code_version.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def code_version; end

  # Sets the attribute code_version
  #
  # @param value the value to set the attribute code_version to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def code_version=(_arg0); end

  # Returns the value of attribute collect_user_ip.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def collect_user_ip; end

  # Sets the attribute collect_user_ip
  #
  # @param value the value to set the attribute collect_user_ip to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def collect_user_ip=(_arg0); end

  # Returns the value of attribute configured_options.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def configured_options; end

  # Sets the attribute configured_options
  #
  # @param value the value to set the attribute configured_options to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def configured_options=(_arg0); end

  # Returns the value of attribute custom_data_method.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def custom_data_method; end

  # Sets the attribute custom_data_method
  #
  # @param value the value to set the attribute custom_data_method to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def custom_data_method=(_arg0); end

  # Returns the value of attribute default_logger.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def default_logger; end

  # Sets the attribute default_logger
  #
  # @param value the value to set the attribute default_logger to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def default_logger=(_arg0); end

  # Returns the value of attribute delayed_job_enabled.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def delayed_job_enabled; end

  # Sets the attribute delayed_job_enabled
  #
  # @param value the value to set the attribute delayed_job_enabled to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def delayed_job_enabled=(_arg0); end

  # Returns the value of attribute disable_action_mailer_monkey_patch.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_action_mailer_monkey_patch; end

  # Sets the attribute disable_action_mailer_monkey_patch
  #
  # @param value the value to set the attribute disable_action_mailer_monkey_patch to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_action_mailer_monkey_patch=(_arg0); end

  # Returns the value of attribute disable_core_monkey_patch.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_core_monkey_patch; end

  # Sets the attribute disable_core_monkey_patch
  #
  # @param value the value to set the attribute disable_core_monkey_patch to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_core_monkey_patch=(_arg0); end

  # Returns the value of attribute disable_monkey_patch.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_monkey_patch; end

  # Sets the attribute disable_monkey_patch
  #
  # @param value the value to set the attribute disable_monkey_patch to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_monkey_patch=(_arg0); end

  # Returns the value of attribute disable_rack_monkey_patch.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_rack_monkey_patch; end

  # Sets the attribute disable_rack_monkey_patch
  #
  # @param value the value to set the attribute disable_rack_monkey_patch to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def disable_rack_monkey_patch=(_arg0); end

  # Returns the value of attribute dj_threshold.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def dj_threshold; end

  # Sets the attribute dj_threshold
  #
  # @param value the value to set the attribute dj_threshold to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def dj_threshold=(_arg0); end

  # Returns the value of attribute dj_use_scoped_block.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def dj_use_scoped_block; end

  # Sets the attribute dj_use_scoped_block
  #
  # @param value the value to set the attribute dj_use_scoped_block to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def dj_use_scoped_block=(_arg0); end

  # Returns the value of attribute enable_error_context.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def enable_error_context; end

  # Sets the attribute enable_error_context
  #
  # @param value the value to set the attribute enable_error_context to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def enable_error_context=(_arg0); end

  # Returns the value of attribute enable_rails_error_subscriber.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def enable_rails_error_subscriber; end

  # source://rollbar//lib/rollbar/configuration.rb#342
  def enable_rails_error_subscriber=(enable); end

  # Returns the value of attribute enabled.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def enabled; end

  # Sets the attribute enabled
  #
  # @param value the value to set the attribute enabled to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def enabled=(_arg0); end

  # Returns the value of attribute endpoint.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def endpoint; end

  # Sets the attribute endpoint
  #
  # @param value the value to set the attribute endpoint to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def endpoint=(_arg0); end

  # Returns the value of attribute environment.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def environment; end

  # Sets the attribute environment
  #
  # @param value the value to set the attribute environment to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def environment=(_arg0); end

  # Returns the value of attribute exception_level_filters.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def exception_level_filters; end

  # Sets the attribute exception_level_filters
  #
  # @param value the value to set the attribute exception_level_filters to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def exception_level_filters=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#385
  def execute_hook(symbol, *args); end

  # Returns the value of attribute failover_handlers.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def failover_handlers; end

  # Sets the attribute failover_handlers
  #
  # @param value the value to set the attribute failover_handlers to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def failover_handlers=(_arg0); end

  # Returns the value of attribute filepath.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def filepath; end

  # Sets the attribute filepath
  #
  # @param value the value to set the attribute filepath to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def filepath=(_arg0); end

  # Returns the value of attribute files_processed_duration.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_duration; end

  # Sets the attribute files_processed_duration
  #
  # @param value the value to set the attribute files_processed_duration to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_duration=(_arg0); end

  # Returns the value of attribute files_processed_enabled.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_enabled; end

  # Sets the attribute files_processed_enabled
  #
  # @param value the value to set the attribute files_processed_enabled to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_enabled=(_arg0); end

  # Returns the value of attribute files_processed_size.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_size; end

  # Sets the attribute files_processed_size
  #
  # @param value the value to set the attribute files_processed_size to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_processed_size=(_arg0); end

  # Returns the value of attribute files_with_pid_name_enabled.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_with_pid_name_enabled; end

  # Sets the attribute files_with_pid_name_enabled
  #
  # @param value the value to set the attribute files_with_pid_name_enabled to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def files_with_pid_name_enabled=(_arg0); end

  # Returns the value of attribute framework.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def framework; end

  # Sets the attribute framework
  #
  # @param value the value to set the attribute framework to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def framework=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#373
  def hook(symbol, &block); end

  # Returns the value of attribute host.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def host; end

  # Sets the attribute host
  #
  # @param value the value to set the attribute host to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def host=(_arg0); end

  # Returns the value of attribute ignore_internal_errors.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def ignore_internal_errors; end

  # Sets the attribute ignore_internal_errors
  #
  # @param value the value to set the attribute ignore_internal_errors to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def ignore_internal_errors=(_arg0); end

  # Returns the value of attribute ignored_person_ids.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def ignored_person_ids; end

  # Sets the attribute ignored_person_ids
  #
  # @param value the value to set the attribute ignored_person_ids to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def ignored_person_ids=(_arg0); end

  # Returns the value of attribute js_enabled.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def js_enabled; end

  # Sets the attribute js_enabled
  #
  # @param value the value to set the attribute js_enabled to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def js_enabled=(_arg0); end

  # Returns the value of attribute js_options.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def js_options; end

  # Sets the attribute js_options
  #
  # @param value the value to set the attribute js_options to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def js_options=(_arg0); end

  # Returns the value of attribute locals.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def locals; end

  # Sets the attribute locals
  #
  # @param value the value to set the attribute locals to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def locals=(_arg0); end

  # Returns the value of attribute log_payload.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def log_payload; end

  # Sets the attribute log_payload
  #
  # @param value the value to set the attribute log_payload to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def log_payload=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#369
  def logger; end

  # seconds # bytes
  #
  # source://rollbar//lib/rollbar/configuration.rb#85
  def logger=(_arg0); end

  # Returns the value of attribute logger_level.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def logger_level; end

  # source://rollbar//lib/rollbar/configuration.rb#361
  def logger_level=(level); end

  # source://rollbar//lib/rollbar/configuration.rb#208
  def merge(options); end

  # source://rollbar//lib/rollbar/configuration.rb#215
  def merge!(options); end

  # Returns the value of attribute net_retries.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def net_retries; end

  # Sets the attribute net_retries
  #
  # @param value the value to set the attribute net_retries to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def net_retries=(_arg0); end

  # Returns the value of attribute open_timeout.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def open_timeout; end

  # Sets the attribute open_timeout
  #
  # @param value the value to set the attribute open_timeout to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def open_timeout=(_arg0); end

  def original_clone(freeze: T.unsafe(nil)); end

  # Returns the value of attribute payload_options.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def payload_options; end

  # Sets the attribute payload_options
  #
  # @param value the value to set the attribute payload_options to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def payload_options=(_arg0); end

  # Returns the value of attribute person_email_method.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_email_method; end

  # Sets the attribute person_email_method
  #
  # @param value the value to set the attribute person_email_method to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_email_method=(_arg0); end

  # Returns the value of attribute person_id_method.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_id_method; end

  # Sets the attribute person_id_method
  #
  # @param value the value to set the attribute person_id_method to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_id_method=(_arg0); end

  # Returns the value of attribute person_method.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_method; end

  # Sets the attribute person_method
  #
  # @param value the value to set the attribute person_method to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_method=(_arg0); end

  # Returns the value of attribute person_username_method.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_username_method; end

  # Sets the attribute person_username_method
  #
  # @param value the value to set the attribute person_username_method to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def person_username_method=(_arg0); end

  # Returns the value of attribute populate_empty_backtraces.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def populate_empty_backtraces; end

  # Sets the attribute populate_empty_backtraces
  #
  # @param value the value to set the attribute populate_empty_backtraces to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def populate_empty_backtraces=(_arg0); end

  # Returns the value of attribute project_gem_paths.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def project_gem_paths; end

  # source://rollbar//lib/rollbar/configuration.rb#311
  def project_gems=(gems); end

  # Returns the value of attribute proxy.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def proxy; end

  # Sets the attribute proxy
  #
  # @param value the value to set the attribute proxy to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def proxy=(_arg0); end

  # Returns the value of attribute raise_on_error.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def raise_on_error; end

  # Sets the attribute raise_on_error
  #
  # @param value the value to set the attribute raise_on_error to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def raise_on_error=(_arg0); end

  # Returns the value of attribute randomize_scrub_length.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def randomize_scrub_length; end

  # Sets the attribute randomize_scrub_length
  #
  # @param value the value to set the attribute randomize_scrub_length to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def randomize_scrub_length=(_arg0); end

  # Returns the value of attribute report_dj_data.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def report_dj_data; end

  # Sets the attribute report_dj_data
  #
  # @param value the value to set the attribute report_dj_data to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def report_dj_data=(_arg0); end

  # Returns the value of attribute request_timeout.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def request_timeout; end

  # Sets the attribute request_timeout
  #
  # @param value the value to set the attribute request_timeout to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def request_timeout=(_arg0); end

  # Returns the value of attribute root.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def root; end

  # Sets the attribute root
  #
  # @param value the value to set the attribute root to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def root=(_arg0); end

  # Returns the value of attribute safely.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def safely; end

  # Sets the attribute safely
  #
  # @param value the value to set the attribute safely to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def safely=(_arg0); end

  # Returns the value of attribute safely.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def safely?; end

  # Returns the value of attribute scrub_fields.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_fields; end

  # Sets the attribute scrub_fields
  #
  # @param value the value to set the attribute scrub_fields to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_fields=(_arg0); end

  # Returns the value of attribute scrub_headers.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_headers; end

  # Sets the attribute scrub_headers
  #
  # @param value the value to set the attribute scrub_headers to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_headers=(_arg0); end

  # Returns the value of attribute scrub_password.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_password; end

  # Sets the attribute scrub_password
  #
  # @param value the value to set the attribute scrub_password to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_password=(_arg0); end

  # Returns the value of attribute scrub_user.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_user; end

  # Sets the attribute scrub_user
  #
  # @param value the value to set the attribute scrub_user to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_user=(_arg0); end

  # Returns the value of attribute scrub_whitelist.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_whitelist; end

  # Sets the attribute scrub_whitelist
  #
  # @param value the value to set the attribute scrub_whitelist to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def scrub_whitelist=(_arg0); end

  # Returns the value of attribute send_extra_frame_data.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def send_extra_frame_data; end

  # source://rollbar//lib/rollbar/configuration.rb#330
  def send_extra_frame_data=(value); end

  # Returns the value of attribute sidekiq_threshold.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def sidekiq_threshold; end

  # Sets the attribute sidekiq_threshold
  #
  # @param value the value to set the attribute sidekiq_threshold to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def sidekiq_threshold=(_arg0); end

  # Returns the value of attribute sidekiq_use_scoped_block.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def sidekiq_use_scoped_block; end

  # Sets the attribute sidekiq_use_scoped_block
  #
  # @param value the value to set the attribute sidekiq_use_scoped_block to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def sidekiq_use_scoped_block=(_arg0); end

  # Returns the value of attribute transform.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def transform; end

  # source://rollbar//lib/rollbar/configuration.rb#326
  def transform=(*handler); end

  # Returns the value of attribute transmit.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def transmit; end

  # Sets the attribute transmit
  #
  # @param value the value to set the attribute transmit to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def transmit=(_arg0); end

  # Returns the value of attribute uncaught_exception_level.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def uncaught_exception_level; end

  # Sets the attribute uncaught_exception_level
  #
  # @param value the value to set the attribute uncaught_exception_level to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def uncaught_exception_level=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#226
  def use_active_job(options = T.unsafe(nil)); end

  # Returns the value of attribute use_async.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_async; end

  # Sets the attribute use_async
  #
  # @param value the value to set the attribute use_async to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_async=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#236
  def use_delayed_job(options = T.unsafe(nil)); end

  # Returns the value of attribute use_eventmachine.
  #
  # source://rollbar//lib/rollbar/configuration.rb#78
  def use_eventmachine; end

  # source://rollbar//lib/rollbar/configuration.rb#306
  def use_eventmachine=(value); end

  # Returns the value of attribute use_exception_level_filters_default.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_exception_level_filters_default; end

  # Sets the attribute use_exception_level_filters_default
  #
  # @param value the value to set the attribute use_exception_level_filters_default to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_exception_level_filters_default=(_arg0); end

  # Returns the value of attribute use_payload_access_token.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_payload_access_token; end

  # Sets the attribute use_payload_access_token
  #
  # @param value the value to set the attribute use_payload_access_token to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def use_payload_access_token=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#251
  def use_resque(options = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/configuration.rb#260
  def use_shoryuken(options = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/configuration.rb#245
  def use_sidekiq(options = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/configuration.rb#269
  def use_sidekiq=(value); end

  # source://rollbar//lib/rollbar/configuration.rb#288
  def use_sucker_punch; end

  # source://rollbar//lib/rollbar/configuration.rb#294
  def use_sucker_punch=(_value); end

  # source://rollbar//lib/rollbar/configuration.rb#281
  def use_thread(options = T.unsafe(nil)); end

  # Returns the value of attribute user_ip_obfuscator_secret.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def user_ip_obfuscator_secret; end

  # Sets the attribute user_ip_obfuscator_secret
  #
  # @param value the value to set the attribute user_ip_obfuscator_secret to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def user_ip_obfuscator_secret=(_arg0); end

  # Returns the value of attribute user_ip_rack_env_key.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def user_ip_rack_env_key; end

  # Sets the attribute user_ip_rack_env_key
  #
  # @param value the value to set the attribute user_ip_rack_env_key to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def user_ip_rack_env_key=(_arg0); end

  # Returns the value of attribute verify_ssl_peer.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def verify_ssl_peer; end

  # Sets the attribute verify_ssl_peer
  #
  # @param value the value to set the attribute verify_ssl_peer to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def verify_ssl_peer=(_arg0); end

  # Returns the value of attribute web_base.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def web_base; end

  # Sets the attribute web_base
  #
  # @param value the value to set the attribute web_base to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def web_base=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#199
  def wrapped_clone; end

  # Returns the value of attribute write_to_file.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def write_to_file; end

  # Sets the attribute write_to_file
  #
  # @param value the value to set the attribute write_to_file to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#7
  def write_to_file=(_arg0); end

  private

  # source://rollbar//lib/rollbar/configuration.rb#190
  def initialize_copy(orig); end
end

# source://rollbar//lib/rollbar/configuration.rb#89
Rollbar::Configuration::DEFAULT_ENDPOINT = T.let(T.unsafe(nil), String)

# source://rollbar//lib/rollbar/configuration.rb#90
Rollbar::Configuration::DEFAULT_WEB_BASE = T.let(T.unsafe(nil), String)

# source://rollbar//lib/rollbar/configuration.rb#5
Rollbar::Configuration::SEND_EXTRA_FRAME_DATA_OPTIONS = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/configuration.rb#390
class Rollbar::ConfiguredOptions
  # @return [ConfiguredOptions] a new instance of ConfiguredOptions
  #
  # source://rollbar//lib/rollbar/configuration.rb#393
  def initialize(configuration); end

  # Returns the value of attribute configuration.
  #
  # source://rollbar//lib/rollbar/configuration.rb#391
  def configuration; end

  # Sets the attribute configuration
  #
  # @param value the value to set the attribute configuration to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#391
  def configuration=(_arg0); end

  # Returns the value of attribute configured.
  #
  # source://rollbar//lib/rollbar/configuration.rb#391
  def configured; end

  # Sets the attribute configured
  #
  # @param value the value to set the attribute configured to.
  #
  # source://rollbar//lib/rollbar/configuration.rb#391
  def configured=(_arg0); end

  # source://rollbar//lib/rollbar/configuration.rb#398
  def method_missing(method, *args, &block); end

  private

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/configuration.rb#410
  def respond_to_missing?(method); end
end

# source://rollbar//lib/rollbar/delay/girl_friday.rb#2
module Rollbar::Delay; end

# source://rollbar//lib/rollbar/delay/girl_friday.rb#3
class Rollbar::Delay::GirlFriday
  # source://rollbar//lib/rollbar/delay/girl_friday.rb#22
  def call(payload); end

  class << self
    # source://rollbar//lib/rollbar/delay/girl_friday.rb#9
    def call(payload); end

    # source://rollbar//lib/rollbar/delay/girl_friday.rb#13
    def queue; end

    # source://rollbar//lib/rollbar/delay/girl_friday.rb#5
    def queue_class; end
  end
end

# source://rollbar//lib/rollbar/delay/thread.rb#5
class Rollbar::Delay::Thread
  # source://rollbar//lib/rollbar/delay/thread.rb#76
  def call(payload); end

  # source://rollbar//lib/rollbar/delay/thread.rb#72
  def priority; end

  class << self
    # source://rollbar//lib/rollbar/delay/thread.rb#18
    def call(payload); end

    # source://rollbar//lib/rollbar/delay/thread.rb#26
    def options; end

    # Sets the attribute options
    #
    # @param value the value to set the attribute options to.
    #
    # source://rollbar//lib/rollbar/delay/thread.rb#15
    def options=(_arg0); end

    # Returns the value of attribute reaper.
    #
    # source://rollbar//lib/rollbar/delay/thread.rb#16
    def reaper; end

    private

    # source://rollbar//lib/rollbar/delay/thread.rb#45
    def build_reaper_thread; end

    # source://rollbar//lib/rollbar/delay/thread.rb#57
    def configure_exit_handler; end

    # source://rollbar//lib/rollbar/delay/thread.rb#36
    def spawn_threads_reaper; end

    # source://rollbar//lib/rollbar/delay/thread.rb#32
    def threads; end
  end
end

# source://rollbar//lib/rollbar/delay/thread.rb#12
Rollbar::Delay::Thread::DEFAULT_PRIORITY = T.let(T.unsafe(nil), Integer)

# source://rollbar//lib/rollbar/delay/thread.rb#6
Rollbar::Delay::Thread::EXIT_SIGNAL = T.let(T.unsafe(nil), Symbol)

# source://rollbar//lib/rollbar/delay/thread.rb#7
Rollbar::Delay::Thread::EXIT_TIMEOUT = T.let(T.unsafe(nil), Integer)

# source://rollbar//lib/rollbar/delay/thread.rb#9
class Rollbar::Delay::Thread::Error < ::StandardError; end

# source://rollbar//lib/rollbar/delay/thread.rb#10
class Rollbar::Delay::Thread::TimeoutError < ::Rollbar::Delay::Thread::Error; end

# source://rollbar//lib/rollbar/encoding.rb#2
module Rollbar::Encoding
  class << self
    # source://rollbar//lib/rollbar/encoding.rb#12
    def encode(object); end

    # Returns the value of attribute encoding_class.
    #
    # source://rollbar//lib/rollbar/encoding.rb#4
    def encoding_class; end

    # Sets the attribute encoding_class
    #
    # @param value the value to set the attribute encoding_class to.
    #
    # source://rollbar//lib/rollbar/encoding.rb#4
    def encoding_class=(_arg0); end

    # source://rollbar//lib/rollbar/encoding.rb#7
    def setup; end
  end
end

# source://rollbar//lib/rollbar/encoding/encoder.rb#3
class Rollbar::Encoding::Encoder
  # @return [Encoder] a new instance of Encoder
  #
  # source://rollbar//lib/rollbar/encoding/encoder.rb#13
  def initialize(object); end

  # source://rollbar//lib/rollbar/encoding/encoder.rb#17
  def encode; end

  # Returns the value of attribute object.
  #
  # source://rollbar//lib/rollbar/encoding/encoder.rb#11
  def object; end

  # Sets the attribute object
  #
  # @param value the value to set the attribute object to.
  #
  # source://rollbar//lib/rollbar/encoding/encoder.rb#11
  def object=(_arg0); end

  private

  # source://rollbar//lib/rollbar/encoding/encoder.rb#52
  def detect_encoding(v); end

  # source://rollbar//lib/rollbar/encoding/encoder.rb#66
  def encoding_args(value); end

  # source://rollbar//lib/rollbar/encoding/encoder.rb#42
  def force_encoding(value); end
end

# source://rollbar//lib/rollbar/encoding/encoder.rb#4
Rollbar::Encoding::Encoder::ALL_ENCODINGS = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/encoding/encoder.rb#6
Rollbar::Encoding::Encoder::ASCII_ENCODINGS = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/encoding/encoder.rb#9
Rollbar::Encoding::Encoder::BINARY = T.let(T.unsafe(nil), String)

# source://rollbar//lib/rollbar/encoding/encoder.rb#8
Rollbar::Encoding::Encoder::UTF8 = T.let(T.unsafe(nil), String)

# source://rollbar//lib/rollbar/plugins/rails/error_subscriber.rb#2
class Rollbar::ErrorSubscriber
  # source://rollbar//lib/rollbar/plugins/rails/error_subscriber.rb#3
  def report(error, handled:, severity:, context:, source: T.unsafe(nil)); end
end

# source://rollbar//lib/rollbar/exceptions.rb#2
class Rollbar::Ignore < ::StandardError; end

# This class represents the payload to be sent to the API.
# It contains the logic to build the payload, trucante it
# and dump the JSON.
#
# source://rollbar//lib/rollbar/item/locals.rb#5
class Rollbar::Item
  extend ::Forwardable

  # @return [Item] a new instance of Item
  #
  # source://rollbar//lib/rollbar/item.rb#39
  def initialize(options); end

  # source://forwardable/1.3.2/forwardable.rb#229
  def [](*args, **_arg1, &block); end

  # source://rollbar//lib/rollbar/item.rb#174
  def add_access_token_to_payload(payload); end

  # source://rollbar//lib/rollbar/item.rb#56
  def build; end

  # source://rollbar//lib/rollbar/item.rb#65
  def build_data; end

  # source://rollbar//lib/rollbar/item.rb#97
  def build_optional_data(data); end

  # Returns the value of attribute configuration.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def configuration; end

  # source://rollbar//lib/rollbar/item.rb#109
  def configured_options; end

  # Returns the value of attribute context.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def context; end

  # source://rollbar//lib/rollbar/item.rb#127
  def dump; end

  # Returns the value of attribute exception.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def exception; end

  # Returns the value of attribute extra.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def extra; end

  # source://rollbar//lib/rollbar/item.rb#141
  def handle_too_large_payload(stringified_payload, _final_payload, attempts); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/item.rb#165
  def ignored?; end

  # source://rollbar//lib/rollbar/item.rb#80
  def initial_data; end

  # Returns the value of attribute level.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def level; end

  # Returns the value of attribute logger.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def logger; end

  # Returns the value of attribute message.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def message; end

  # Returns the value of attribute notifier.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def notifier; end

  # source://rollbar//lib/rollbar/item.rb#52
  def payload; end

  # Sets the attribute payload
  #
  # @param value the value to set the attribute payload to.
  #
  # source://rollbar//lib/rollbar/item.rb#24
  def payload=(_arg0); end

  # Returns the value of attribute scope.
  #
  # source://rollbar//lib/rollbar/item.rb#26
  def scope; end

  # source://rollbar//lib/rollbar/item.rb#159
  def too_large_payload_string(attempts); end

  private

  # source://rollbar//lib/rollbar/item.rb#203
  def build_backtrace_body; end

  # source://rollbar//lib/rollbar/item.rb#199
  def build_body; end

  # source://rollbar//lib/rollbar/item.rb#192
  def build_environment; end

  # source://rollbar//lib/rollbar/item.rb#212
  def build_extra; end

  # source://rollbar//lib/rollbar/item.rb#266
  def build_message_body; end

  # source://rollbar//lib/rollbar/item.rb#242
  def custom_data; end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/item.rb#238
  def custom_data_method?; end

  # source://rollbar//lib/rollbar/item.rb#285
  def enforce_valid_utf8; end

  # source://rollbar//lib/rollbar/item.rb#223
  def error_context; end

  # source://rollbar//lib/rollbar/item.rb#256
  def report_custom_data_error(e); end

  # source://rollbar//lib/rollbar/item.rb#227
  def scrub(data); end

  # source://rollbar//lib/rollbar/item.rb#274
  def server_data; end

  # source://rollbar//lib/rollbar/item.rb#289
  def transform; end

  # source://rollbar//lib/rollbar/item.rb#303
  def transform_options; end

  class << self
    # source://rollbar//lib/rollbar/item.rb#32
    def build_with(payload, options = T.unsafe(nil)); end
  end
end

# source://rollbar//lib/rollbar/item/backtrace.rb#5
class Rollbar::Item::Backtrace
  # @return [Backtrace] a new instance of Backtrace
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#10
  def initialize(exception, options = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/item/backtrace.rb#18
  def build; end

  # Returns the value of attribute configuration.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#6
  def configuration; end

  # Returns the value of attribute exception.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#6
  def exception; end

  # Returns the value of attribute extra.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#6
  def extra; end

  # source://rollbar//lib/rollbar/item/backtrace.rb#33
  def get_file_lines(filename); end

  # Returns the value of attribute message.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#6
  def message; end

  # source://rollbar//lib/rollbar/item/backtrace.rb#18
  def to_h; end

  private

  # source://rollbar//lib/rollbar/item/backtrace.rb#83
  def cleaned_backtrace(current_exception); end

  # Returns the backtrace to be sent to our API. There are 3 options:
  #
  # 1. The exception received has a backtrace, then that backtrace is returned.
  # 2. configuration.populate_empty_backtraces is disabled, we return [] here
  # 3. The user has configuration.populate_empty_backtraces is enabled, then:
  #
  # We want to send the caller as backtrace, but the first lines of that array
  # are those from the user's Rollbar.error line until this method. We want
  # to remove those lines.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#101
  def exception_backtrace(current_exception); end

  # Returns the value of attribute files.
  #
  # source://rollbar//lib/rollbar/item/backtrace.rb#6
  def files; end

  # source://rollbar//lib/rollbar/item/backtrace.rb#75
  def map_frames(current_exception); end

  # source://rollbar//lib/rollbar/item/backtrace.rb#39
  def read_file(filename); end

  # source://rollbar//lib/rollbar/item/backtrace.rb#112
  def rollbar_lib_gem_dir; end

  # source://rollbar//lib/rollbar/item/backtrace.rb#47
  def trace_chain; end

  # source://rollbar//lib/rollbar/item/backtrace.rb#65
  def trace_data(current_exception); end
end

# Representation of the trace data per frame in the payload
#
# source://rollbar//lib/rollbar/item/frame.rb#8
class Rollbar::Item::Frame
  # @return [Frame] a new instance of Frame
  #
  # source://rollbar//lib/rollbar/item/frame.rb#13
  def initialize(backtrace, frame, options = T.unsafe(nil)); end

  # Returns the value of attribute backtrace.
  #
  # source://rollbar//lib/rollbar/item/frame.rb#9
  def backtrace; end

  # Returns the value of attribute configuration.
  #
  # source://rollbar//lib/rollbar/item/frame.rb#9
  def configuration; end

  # Returns the value of attribute frame.
  #
  # source://rollbar//lib/rollbar/item/frame.rb#9
  def frame; end

  # source://rollbar//lib/rollbar/item/frame.rb#19
  def to_h; end

  private

  # source://rollbar//lib/rollbar/item/frame.rb#90
  def code_data(file_lines, lineno); end

  # source://rollbar//lib/rollbar/item/frame.rb#94
  def context_data(file_lines, lineno); end

  # source://rollbar//lib/rollbar/item/frame.rb#46
  def extra_frame_data(filename, lineno); end

  # source://rollbar//lib/rollbar/item/frame.rb#101
  def locals_data(filename, lineno); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/item/frame.rb#69
  def outside_project?(filename); end

  # source://rollbar//lib/rollbar/item/frame.rb#107
  def post_data(file_lines, lineno); end

  # source://rollbar//lib/rollbar/item/frame.rb#115
  def pre_data(file_lines, lineno); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/item/frame.rb#58
  def skip_extra_frame_data?(filename, file_lines); end

  # source://rollbar//lib/rollbar/item/frame.rb#42
  def unknown_frame; end
end

# source://rollbar//lib/rollbar/item/frame.rb#11
Rollbar::Item::Frame::MAX_CONTEXT_LENGTH = T.let(T.unsafe(nil), Integer)

# source://rollbar//lib/rollbar/item/locals.rb#6
class Rollbar::Item::Locals
  class << self
    # source://rollbar//lib/rollbar/item/locals.rb#8
    def exception_frames; end

    # source://rollbar//lib/rollbar/item/locals.rb#20
    def frame_for_location(filename, lineno); end

    # source://rollbar//lib/rollbar/item/locals.rb#12
    def locals_for_location(filename, lineno); end

    private

    # source://rollbar//lib/rollbar/item/locals.rb#34
    def locals_for(frame); end

    # @return [Boolean]
    #
    # source://rollbar//lib/rollbar/item/locals.rb#30
    def matching_frame?(frame, filename, lineno); end

    # Prepare objects to be handled by the payload serializer.
    #
    # Hashes and Arrays are traversed. Then all types execpt strings and
    # immediates are exported using #inspect. Sending the object itself to the
    # serializer can result in large recursive expansions, especially in Rails
    # environments with ActiveRecord, ActiveSupport, etc. on the stack.
    # Other export options could be #to_s, #to_h, and #as_json. Several of these
    # will omit the class name, or are not implemented for many types.
    #
    # #inspect has the advantage that it is specifically intended for debugging
    # output. If the user wants more or different information in the payload
    # about a specific type, #inspect is the correct place to implement it.
    # Likewise the default implementation should be oriented toward usefulness
    # in debugging.
    #
    # Because #inspect outputs a string, it can be handled well by the string
    # truncation strategy for large payloads.
    #
    # source://rollbar//lib/rollbar/item/locals.rb#62
    def prepare_value(value); end

    # source://rollbar//lib/rollbar/item/locals.rb#93
    def scrub(hash); end

    # source://rollbar//lib/rollbar/item/locals.rb#75
    def simple_classes; end

    # @return [Boolean]
    #
    # source://rollbar//lib/rollbar/item/locals.rb#83
    def simple_value?(value); end
  end
end

# source://rollbar//lib/rollbar/json.rb#5
module Rollbar::JSON
  private

  # source://rollbar//lib/rollbar/json.rb#8
  def dump(object); end

  # source://rollbar//lib/rollbar/json.rb#14
  def load(string); end

  class << self
    # source://rollbar//lib/rollbar/json.rb#8
    def dump(object); end

    # source://rollbar//lib/rollbar/json.rb#14
    def load(string); end
  end
end

# source://rollbar//lib/rollbar/plugins/rails.rb#24
module Rollbar::Js; end

# source://rollbar//lib/rollbar/plugins/rails.rb#25
module Rollbar::Js::Frameworks; end

# source://rollbar//lib/rollbar/plugins/rails.rb#32
class Rollbar::Js::Frameworks::Rails
  # source://rollbar//lib/rollbar/plugins/rails.rb#41
  def after_secure_headers(&block); end

  # source://rollbar//lib/rollbar/plugins/rails.rb#33
  def load(plugin); end

  # source://rollbar//lib/rollbar/plugins/rails.rb#46
  def plugin_execute_proc_body(plugin); end

  # source://rollbar//lib/rollbar/plugins/rails.rb#63
  def secure_headers_middleware?; end
end

# source://rollbar//lib/rollbar/language_support.rb#2
module Rollbar::LanguageSupport
  private

  # source://rollbar//lib/rollbar/language_support.rb#5
  def const_defined?(mod, target, inherit = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/language_support.rb#9
  def const_get(mod, target, inherit = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/language_support.rb#19
  def timeout_exceptions; end

  # source://rollbar//lib/rollbar/language_support.rb#13
  def version?(version); end

  class << self
    # @return [Boolean]
    #
    # source://rollbar//lib/rollbar/language_support.rb#5
    def const_defined?(mod, target, inherit = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/language_support.rb#9
    def const_get(mod, target, inherit = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/language_support.rb#19
    def timeout_exceptions; end

    # @return [Boolean]
    #
    # source://rollbar//lib/rollbar/language_support.rb#13
    def version?(version); end
  end
end

# source://rollbar//lib/rollbar/lazy_store.rb#2
class Rollbar::LazyStore
  # @return [LazyStore] a new instance of LazyStore
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#6
  def initialize(initial_data); end

  # source://rollbar//lib/rollbar/lazy_store.rb#21
  def ==(other); end

  # source://rollbar//lib/rollbar/lazy_store.rb#34
  def [](key); end

  # source://rollbar//lib/rollbar/lazy_store.rb#38
  def []=(key, value); end

  # With this version of clone we ensure that the loaded_data is empty
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#30
  def clone; end

  # source://rollbar//lib/rollbar/lazy_store.rb#44
  def data; end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#13
  def eql?(other); end

  # Returns the value of attribute raw.
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#3
  def raw; end

  private

  # source://rollbar//lib/rollbar/lazy_store.rb#64
  def find_value(key); end

  # source://rollbar//lib/rollbar/lazy_store.rb#54
  def load_value(key); end

  # Returns the value of attribute loaded_data.
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#3
  def loaded_data; end

  # source://rollbar//lib/rollbar/lazy_store.rb#69
  def method_missing(method_sym, *args, &block); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/lazy_store.rb#75
  def respond_to_missing?(method_sym, include_all); end
end

# source://rollbar//lib/rollbar/logger_proxy.rb#2
class Rollbar::LoggerProxy
  # @return [LoggerProxy] a new instance of LoggerProxy
  #
  # source://rollbar//lib/rollbar/logger_proxy.rb#5
  def initialize(object); end

  # source://rollbar//lib/rollbar/logger_proxy.rb#9
  def debug(message); end

  # source://rollbar//lib/rollbar/logger_proxy.rb#21
  def error(message); end

  # source://rollbar//lib/rollbar/logger_proxy.rb#13
  def info(message); end

  # source://rollbar//lib/rollbar/logger_proxy.rb#25
  def log(level, message); end

  # Returns the value of attribute object.
  #
  # source://rollbar//lib/rollbar/logger_proxy.rb#3
  def object; end

  # source://rollbar//lib/rollbar/logger_proxy.rb#17
  def warn(message); end

  protected

  # source://rollbar//lib/rollbar/logger_proxy.rb#38
  def acceptable_levels; end
end

# The notifier class. It has the core functionality
# for sending reports to the API.
#
# source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#2
class Rollbar::Notifier
  # @return [Notifier] a new instance of Notifier
  #
  # source://rollbar//lib/rollbar/notifier.rb#23
  def initialize(parent_notifier = T.unsafe(nil), payload_options = T.unsafe(nil), scope = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/notifier.rb#351
  def add_configured_options(payload_notifier, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#338
  def add_original_error(diagnostic, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#361
  def add_original_host(diagnostic, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#329
  def add_original_message(diagnostic, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#365
  def add_original_uuid(diagnostic, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#267
  def build_item_with_payload(payload); end

  # Returns the value of attribute configuration.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def configuration; end

  # Sets the attribute configuration
  #
  # @param value the value to set the attribute configuration to.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def configuration=(_arg0); end

  # Configures the notifier instance
  #
  # @yield [configuration.configured_options]
  #
  # source://rollbar//lib/rollbar/notifier.rb#50
  def configure; end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#200
  def critical(*args); end

  # source://rollbar//lib/rollbar/notifier.rb#388
  def current_bindings; end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#175
  def debug(*args); end

  # source://rollbar//lib/rollbar/notifier.rb#401
  def disable_locals; end

  # source://rollbar//lib/rollbar/notifier.rb#397
  def enable_locals; end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#392
  def enable_locals?; end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#204
  def enabled?; end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#195
  def error(*args); end

  # source://rollbar//lib/rollbar/notifier.rb#384
  def exception_bindings; end

  # source://rollbar//lib/rollbar/notifier.rb#317
  def failsafe_add_original_error_data(payload_notifier, original_error); end

  # source://rollbar//lib/rollbar/notifier.rb#273
  def failsafe_initial_data(exception_reason); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#149
  def ignore_before_process?(level, exception, message, extra); end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#180
  def info(*args); end

  # Returns the value of attribute last_report.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def last_report; end

  # Sets the attribute last_report
  #
  # @param value the value to set the attribute last_report to.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def last_report=(_arg0); end

  # Sends a report to Rollbar.
  #
  # Accepts a level string plus any number of arguments. The last String
  # argument will become the message or description of the report. The last
  # Exception argument will become the associated exception for the report.
  # The last hash argument will be used as the extra data for the report.
  #
  # If the extra hash contains a symbol key :custom_data_method_context
  # the value of the key will be used as the context for
  # configuration.custom_data_method and will be removed from the extra
  # hash.
  #
  # @example
  #   begin
  #   foo = bar
  #   rescue => e
  #   Rollbar.log('error', e)
  #   end
  # @example
  #   Rollbar.log('info', 'This is a simple log message')
  # @example
  #   Rollbar.log('error', e, 'This is a description of the exception')
  #
  # source://rollbar//lib/rollbar/notifier.rb#130
  def log(level, *args); end

  # source://rollbar//lib/rollbar/notifier.rb#371
  def log_debug(message); end

  # source://rollbar//lib/rollbar/notifier.rb#371
  def log_error(message); end

  # source://rollbar//lib/rollbar/notifier.rb#371
  def log_info(message); end

  # source://rollbar//lib/rollbar/notifier.rb#371
  def log_warn(message); end

  # source://rollbar//lib/rollbar/notifier.rb#371
  def log_warning(message); end

  # source://rollbar//lib/rollbar/notifier.rb#376
  def logger; end

  # Similar to configure below, but used only internally within the gem
  # to configure it without initializing any of the third party hooks
  #
  # @yield [configuration.configured_options]
  #
  # source://rollbar//lib/rollbar/notifier.rb#45
  def preconfigure; end

  # source://rollbar//lib/rollbar/notifier.rb#309
  def process_failsafe_item(failsafe_payload); end

  # We will reraise exceptions in this method so async queues
  # can retry the job or, in general, handle an error report some way.
  #
  # At same time that exception is silenced so we don't generate
  # infinite reports. This example is what we want to avoid:
  #
  # 1. New exception in a the project is raised
  # 2. That report enqueued to Sidekiq queue.
  # 3. The Sidekiq job tries to send the report to our API
  # 4. The report fails, for example cause a network failure,
  #    and a exception is raised
  # 5. We report an internal error for that exception
  # 6. We reraise the exception so Sidekiq job fails and
  #    Sidekiq can retry the job reporting the original exception
  # 7. Because the job failed and Sidekiq can be managed by rollbar we'll
  #    report a new exception.
  # 8. Go to point 2.
  #
  # We'll then push to Sidekiq queue indefinitely until the network failure
  # is fixed.
  #
  # Using Rollbar.silenced we avoid the above behavior but Sidekiq
  # will have a chance to retry the original job.
  #
  # source://rollbar//lib/rollbar/notifier.rb#248
  def process_from_async_handler(payload); end

  # source://rollbar//lib/rollbar/notifier.rb#211
  def process_item(item); end

  # @yield [configuration.configured_options]
  #
  # source://rollbar//lib/rollbar/notifier.rb#56
  def reconfigure; end

  # source://rollbar//lib/rollbar/notifier.rb#160
  def report_with_rescue(level, message, exception, extra, context); end

  # source://rollbar//lib/rollbar/notifier.rb#39
  def reset!; end

  # Returns a new notifier with same configuration options
  # but it sets Configuration#safely to true.
  # We are using this flag to avoid having inifite loops
  # when evaluating some custom user methods.
  #
  # source://rollbar//lib/rollbar/notifier.rb#85
  def safely; end

  # source://rollbar//lib/rollbar/notifier.rb#67
  def scope(scope_overrides = T.unsafe(nil), config_overrides = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/notifier.rb#74
  def scope!(options = T.unsafe(nil), config_overrides = T.unsafe(nil)); end

  # Returns the value of attribute scope_object.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def scope_object; end

  # Sets the attribute scope_object
  #
  # @param value the value to set the attribute scope_object to.
  #
  # source://rollbar//lib/rollbar/notifier.rb#17
  def scope_object=(_arg0); end

  # source://rollbar//lib/rollbar/notifier.rb#291
  def send_failsafe(message, exception, original_error = T.unsafe(nil)); end

  # Turns off reporting for the given block.
  #
  # @example
  #   Rollbar.silenced { raise }
  # @yield Block which exceptions won't be reported.
  #
  # source://rollbar//lib/rollbar/notifier.rb#98
  def silenced; end

  # source://rollbar//lib/rollbar/notifier.rb#380
  def trace_with_bindings; end

  # source://rollbar//lib/rollbar/notifier.rb#63
  def unconfigure; end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#185
  def warn(*args); end

  # See log() above
  #
  # source://rollbar//lib/rollbar/notifier.rb#190
  def warning(*args); end

  private

  # source://rollbar//lib/rollbar/notifier.rb#880
  def async_failover(item); end

  # Payload building functions
  #
  # source://rollbar//lib/rollbar/notifier.rb#574
  def build_item(level, message, exception, extra, context); end

  # source://rollbar//lib/rollbar/notifier.rb#415
  def call_before_process(options); end

  # source://rollbar//lib/rollbar/notifier.rb#858
  def default_async_handler; end

  # source://rollbar//lib/rollbar/notifier.rb#650
  def do_post(uri, body, access_token); end

  # source://rollbar//lib/rollbar/notifier.rb#771
  def do_write_item(item); end

  # source://rollbar//lib/rollbar/notifier.rb#607
  def eventmachine_callback(req); end

  # source://rollbar//lib/rollbar/notifier.rb#619
  def eventmachine_errback(req); end

  # source://rollbar//lib/rollbar/notifier.rb#443
  def extract_arguments(args); end

  # source://rollbar//lib/rollbar/notifier.rb#842
  def failsafe_body(reason); end

  # source://rollbar//lib/rollbar/notifier.rb#824
  def failsafe_exception_reason(message, exception); end

  # source://rollbar//lib/rollbar/notifier.rb#815
  def failsafe_reason(message, exception); end

  # source://rollbar//lib/rollbar/notifier.rb#792
  def file_name_with_pid(configuration); end

  # source://rollbar//lib/rollbar/notifier.rb#486
  def filtered_level(exception); end

  # source://rollbar//lib/rollbar/notifier.rb#737
  def handle_net_retries; end

  # source://rollbar//lib/rollbar/notifier.rb#751
  def handle_response(response); end

  # source://rollbar//lib/rollbar/notifier.rb#713
  def http_proxy(uri); end

  # source://rollbar//lib/rollbar/notifier.rb#702
  def http_proxy_for_em(uri); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#478
  def ignored?(exception, use_exception_level_filters = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/notifier.rb#665
  def init_http(uri); end

  # source://rollbar//lib/rollbar/notifier.rb#680
  def init_http_timeouts(http); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#465
  def java_exception?(obj); end

  # source://rollbar//lib/rollbar/notifier.rb#515
  def log_and_return_item_data(item); end

  # source://rollbar//lib/rollbar/notifier.rb#524
  def log_data(data); end

  # source://rollbar//lib/rollbar/notifier.rb#899
  def log_instance_link(data); end

  # source://rollbar//lib/rollbar/notifier.rb#469
  def lookup_exception_level(orig_level, exception, use_exception_level_filters); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#698
  def multibyte?(str); end

  # source://rollbar//lib/rollbar/notifier.rb#733
  def null_proxy; end

  # source://rollbar//lib/rollbar/notifier.rb#433
  def options_for_handler(options); end

  # source://rollbar//lib/rollbar/notifier.rb#685
  def pack_ruby260_bytes(body); end

  # source://rollbar//lib/rollbar/notifier.rb#864
  def process_async_item(item); end

  # source://rollbar//lib/rollbar/notifier.rb#717
  def proxy_from_config; end

  # source://rollbar//lib/rollbar/notifier.rb#729
  def proxy_from_env(uri); end

  # source://rollbar//lib/rollbar/notifier.rb#497
  def report(level, message, exception, extra, context); end

  # Reports an internal error in the Rollbar library. This will be reported
  # within the configured Rollbar project. We'll first attempt to provide a
  # report including the exception traceback. If that fails, we'll fall back
  # to a more static failsafe response.
  #
  # source://rollbar//lib/rollbar/notifier.rb#532
  def report_internal_error(exception, original_error = T.unsafe(nil)); end

  # source://rollbar//lib/rollbar/notifier.rb#846
  def schedule_item(item); end

  # source://rollbar//lib/rollbar/notifier.rb#642
  def send_body(body); end

  # source://rollbar//lib/rollbar/notifier.rb#628
  def send_item(item); end

  # Delivery functions
  #
  # source://rollbar//lib/rollbar/notifier.rb#595
  def send_using_eventmachine(body); end

  # source://rollbar//lib/rollbar/notifier.rb#555
  def skip_reporting_internal_error(exception); end

  # source://rollbar//lib/rollbar/notifier.rb#763
  def ssl_verify_mode; end

  # source://rollbar//lib/rollbar/notifier.rb#800
  def update_file(file, file_name); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#407
  def use_exception_level_filters?(options); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/notifier.rb#908
  def via_failsafe?(item); end
end

# source://rollbar//lib/rollbar/notifier.rb#20
Rollbar::Notifier::EXTENSION_REGEXP = T.let(T.unsafe(nil), Regexp)

# source://rollbar//lib/rollbar/notifier.rb#21
Rollbar::Notifier::FAILSAFE_STRING_LENGTH = T.let(T.unsafe(nil), Integer)

# source://rollbar//lib/rollbar/notifier.rb#19
Rollbar::Notifier::MUTEX = T.let(T.unsafe(nil), Thread::Mutex)

# source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#3
class Rollbar::Notifier::TraceWithBindings
  # @return [TraceWithBindings] a new instance of TraceWithBindings
  #
  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#6
  def initialize; end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#21
  def disable; end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#16
  def enable; end

  # Returns the value of attribute exception_frames.
  #
  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#4
  def exception_frames; end

  # Returns the value of attribute frames.
  #
  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#4
  def frames; end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#10
  def reset; end

  private

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#66
  def binding(trace); end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#32
  def detect_reraise(trace); end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#27
  def exception_signature(trace); end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#56
  def frame(trace); end

  # source://rollbar//lib/rollbar/notifier/trace_with_bindings.rb#36
  def trace_point; end
end

# source://rollbar//lib/rollbar.rb#25
Rollbar::PUBLIC_NOTIFIER_METHODS = T.let(T.unsafe(nil), Array)

# Represents a plugin in the gem. Every plugin can have multiple dependencies
# and multiple execution blocks.
# On Rollbar initialization, all plugins will be saved in memory and those that
# satisfy the dependencies will be loaded
#
# source://rollbar//lib/rollbar/plugin.rb#6
class Rollbar::Plugin
  # @return [Plugin] a new instance of Plugin
  #
  # source://rollbar//lib/rollbar/plugin.rb#12
  def initialize(name); end

  # Returns the value of attribute callables.
  #
  # source://rollbar//lib/rollbar/plugin.rb#7
  def callables; end

  # source://rollbar//lib/rollbar/plugin.rb#25
  def configuration; end

  # Returns the value of attribute dependencies.
  #
  # source://rollbar//lib/rollbar/plugin.rb#7
  def dependencies; end

  # source://rollbar//lib/rollbar/plugin.rb#73
  def execute(&block); end

  # source://rollbar//lib/rollbar/plugin.rb#77
  def execute!; end

  # source://rollbar//lib/rollbar/plugin.rb#49
  def load!; end

  # source://rollbar//lib/rollbar/plugin.rb#21
  def load_on_demand; end

  # source://rollbar//lib/rollbar/plugin.rb#29
  def load_scoped!(transparent = T.unsafe(nil)); end

  # Returns the value of attribute loaded.
  #
  # source://rollbar//lib/rollbar/plugin.rb#8
  def loaded; end

  # Returns the value of attribute name.
  #
  # source://rollbar//lib/rollbar/plugin.rb#7
  def name; end

  # Returns the value of attribute on_demand.
  #
  # source://rollbar//lib/rollbar/plugin.rb#8
  def on_demand; end

  # Sets the attribute on_demand
  #
  # @param value the value to set the attribute on_demand to.
  #
  # source://rollbar//lib/rollbar/plugin.rb#8
  def on_demand=(_arg0); end

  # source://rollbar//lib/rollbar/plugin.rb#81
  def revert(&block); end

  # Returns the value of attribute revert_callables.
  #
  # source://rollbar//lib/rollbar/plugin.rb#7
  def revert_callables; end

  # source://rollbar//lib/rollbar/plugin.rb#61
  def unload!; end

  private

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/plugin.rb#110
  def dependencies_satisfy?; end

  # source://rollbar//lib/rollbar/plugin.rb#87
  def dependency(&block); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/plugin.rb#102
  def load?; end

  # Sets the attribute loaded
  #
  # @param value the value to set the attribute loaded to.
  #
  # source://rollbar//lib/rollbar/plugin.rb#8
  def loaded=(_arg0); end

  # source://rollbar//lib/rollbar/plugin.rb#114
  def log_loading_error(error); end

  # source://rollbar//lib/rollbar/plugin.rb#120
  def log_unloading_error(error); end

  # source://rollbar//lib/rollbar/plugin.rb#91
  def require_dependency(file); end
end

# Stores the available plugin definitions and loads them
#
# source://rollbar//lib/rollbar/plugins.rb#5
class Rollbar::Plugins
  # @return [Plugins] a new instance of Plugins
  #
  # source://rollbar//lib/rollbar/plugins.rb#8
  def initialize; end

  # Returns the value of attribute collection.
  #
  # source://rollbar//lib/rollbar/plugins.rb#6
  def collection; end

  # source://rollbar//lib/rollbar/plugins.rb#22
  def define(name, &block); end

  # source://rollbar//lib/rollbar/plugins.rb#37
  def get(name); end

  # source://rollbar//lib/rollbar/plugins.rb#31
  def load!; end

  # source://rollbar//lib/rollbar/plugins.rb#18
  def plugin_files; end

  # source://rollbar//lib/rollbar/plugins.rb#12
  def require_all; end

  private

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/plugins.rb#43
  def loaded?(name); end
end

# source://rollbar//lib/rollbar/plugins/rails/railtie32.rb#5
class Rollbar::Railtie < ::Rails::Railtie
  include ::Rollbar::RailtieMixin
end

# source://rollbar//lib/rollbar/plugins/rails/railtie_mixin.rb#2
module Rollbar::RailtieMixin
  extend ::ActiveSupport::Concern
end

# source://rollbar//lib/rollbar/plugins/rake.rb#7
module Rollbar::Rake
  class << self
    # source://rollbar//lib/rollbar/plugins/rake.rb#26
    def patch!; end

    # source://rollbar//lib/rollbar/plugins/rake.rb#47
    def patch?; end

    # source://rollbar//lib/rollbar/plugins/rake.rb#9
    def patched; end

    # source://rollbar//lib/rollbar/plugins/rake.rb#9
    def patched=(_arg0); end

    # source://rollbar//lib/rollbar/plugins/rake.rb#56
    def patched?; end

    # source://rollbar//lib/rollbar/plugins/rake.rb#60
    def rake_version; end

    # source://rollbar//lib/rollbar/plugins/rake.rb#42
    def skip_patch; end
  end
end

# source://rollbar//lib/rollbar/plugins/rake.rb#12
module Rollbar::Rake::Handler
  # source://rollbar//lib/rollbar/plugins/rake.rb#20
  def display_error_message_with_rollbar(ex); end

  class << self
    # source://rollbar//lib/rollbar/plugins/rake.rb#13
    def included(base); end
  end
end

# source://rollbar//lib/rollbar/scrubbers.rb#2
module Rollbar::Scrubbers
  private

  # source://rollbar//lib/rollbar/scrubbers.rb#13
  def random_filtered_value; end

  # source://rollbar//lib/rollbar/scrubbers.rb#5
  def scrub_value(_value); end

  class << self
    # source://rollbar//lib/rollbar/scrubbers.rb#13
    def random_filtered_value; end

    # source://rollbar//lib/rollbar/scrubbers.rb#5
    def scrub_value(_value); end
  end
end

# This class contains the logic to scrub the received parameters. It will
# scrub the parameters matching Rollbar.configuration.scrub_fields Array.
# Also, if that configuration option is set to :scrub_all, it will scrub all
# received parameters. It will not scrub anything that is in the scrub_whitelist
# configuration array even if :scrub_all is true.
#
# source://rollbar//lib/rollbar/scrubbers/params.rb#11
class Rollbar::Scrubbers::Params
  # source://rollbar//lib/rollbar/scrubbers/params.rb#21
  def call(options = T.unsafe(nil)); end

  private

  # source://rollbar//lib/rollbar/scrubbers/params.rb#120
  def attachment_value(value); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#46
  def build_fields_regex(config, extra_fields); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#36
  def build_scrub_options(config, extra_fields, whitelist); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#55
  def build_whitelist_regex(whitelist); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#108
  def rollbar_filtered_param_value(value); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#66
  def scrub(params, options); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#98
  def scrub_array(array, options); end

  # source://rollbar//lib/rollbar/scrubbers/params.rb#104
  def scrub_value(value); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/scrubbers/params.rb#128
  def skip_value?(value); end

  class << self
    # source://rollbar//lib/rollbar/scrubbers/params.rb#17
    def call(*args); end
  end
end

# source://rollbar//lib/rollbar/scrubbers/params.rb#13
Rollbar::Scrubbers::Params::ATTACHMENT_CLASSES = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/scrubbers/params.rb#15
Rollbar::Scrubbers::Params::SCRUB_ALL = T.let(T.unsafe(nil), Symbol)

# source://rollbar//lib/rollbar/scrubbers/params.rb#12
Rollbar::Scrubbers::Params::SKIPPED_CLASSES = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/plugins/thread.rb#3
module Rollbar::ThreadPlugin
  # source://rollbar//lib/rollbar/plugins/thread.rb#4
  def initialize(*args); end
end

# source://rollbar//lib/rollbar/truncation/mixin.rb#2
module Rollbar::Truncation
  extend ::Rollbar::Truncation::Mixin

  class << self
    # source://rollbar//lib/rollbar/truncation.rb#24
    def truncate(payload, attempts = T.unsafe(nil)); end
  end
end

# source://rollbar//lib/rollbar/truncation/frames_strategy.rb#6
class Rollbar::Truncation::FramesStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/frames_strategy.rb#13
  def call(payload); end

  # source://rollbar//lib/rollbar/truncation/frames_strategy.rb#26
  def truncate_trace(body); end

  # source://rollbar//lib/rollbar/truncation/frames_strategy.rb#34
  def truncate_trace_chain(body); end

  class << self
    # source://rollbar//lib/rollbar/truncation/frames_strategy.rb#9
    def call(payload); end
  end
end

# 512kb
#
# source://rollbar//lib/rollbar/truncation.rb#15
Rollbar::Truncation::MAX_PAYLOAD_SIZE = T.let(T.unsafe(nil), Integer)

# source://rollbar//lib/rollbar/truncation/min_body_strategy.rb#6
class Rollbar::Truncation::MinBodyStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/min_body_strategy.rb#13
  def call(payload); end

  # source://rollbar//lib/rollbar/truncation/min_body_strategy.rb#27
  def truncate_trace_data(trace_data); end

  class << self
    # source://rollbar//lib/rollbar/truncation/min_body_strategy.rb#9
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation/mixin.rb#3
module Rollbar::Truncation::Mixin
  # source://rollbar//lib/rollbar/truncation/mixin.rb#4
  def dump(payload); end

  # source://rollbar//lib/rollbar/truncation/mixin.rb#12
  def select_frames(frames, range = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://rollbar//lib/rollbar/truncation/mixin.rb#8
  def truncate?(result); end
end

# source://rollbar//lib/rollbar/truncation/raw_strategy.rb#5
class Rollbar::Truncation::RawStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/raw_strategy.rb#12
  def call(payload); end

  class << self
    # source://rollbar//lib/rollbar/truncation/raw_strategy.rb#8
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#5
class Rollbar::Truncation::RemoveAnyKeyStrategy
  include ::Rollbar::Truncation::Mixin

  # @return [RemoveAnyKeyStrategy] a new instance of RemoveAnyKeyStrategy
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#14
  def initialize(payload); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#20
  def call; end

  # Returns the value of attribute data.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def data; end

  # Sets the attribute data
  #
  # @param value the value to set the attribute data to.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def data=(_arg0); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#106
  def data_keys; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#91
  def extract_title(body); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#100
  def extract_title_from_trace(trace); end

  # Returns the value of attribute extracted_title.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def extracted_title; end

  # Sets the attribute extracted_title
  #
  # @param value the value to set the attribute extracted_title to.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def extracted_title=(_arg0); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#82
  def message_key; end

  # Returns the value of attribute payload.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def payload; end

  # Sets the attribute payload
  #
  # @param value the value to set the attribute payload to.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def payload=(_arg0); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#48
  def remove_key_and_return_payload(key); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#38
  def remove_oversized_data_keys; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#30
  def remove_unknown_root_keys; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#60
  def replace_message_body; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#72
  def root_keys; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#114
  def set_key_size(key, hash); end

  # Returns the value of attribute sizes.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def sizes; end

  # Sets the attribute sizes
  #
  # @param value the value to set the attribute sizes to.
  #
  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#8
  def sizes=(_arg0); end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#77
  def skip_keys; end

  # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#65
  def truncation_key; end

  class << self
    # source://rollbar//lib/rollbar/truncation/remove_any_key_strategy.rb#10
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#5
class Rollbar::Truncation::RemoveExtraStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#12
  def call(payload); end

  # source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#22
  def delete_message_extra(body); end

  # source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#26
  def delete_trace_chain_extra(body); end

  # source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#32
  def delete_trace_extra(body); end

  class << self
    # source://rollbar//lib/rollbar/truncation/remove_extra_strategy.rb#8
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation/remove_request_strategy.rb#5
class Rollbar::Truncation::RemoveRequestStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/remove_request_strategy.rb#12
  def call(payload); end

  class << self
    # source://rollbar//lib/rollbar/truncation/remove_request_strategy.rb#8
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation.rb#16
Rollbar::Truncation::STRATEGIES = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/truncation/strings_strategy.rb#6
class Rollbar::Truncation::StringsStrategy
  include ::Rollbar::Truncation::Mixin

  # source://rollbar//lib/rollbar/truncation/strings_strategy.rb#15
  def call(payload); end

  # source://rollbar//lib/rollbar/truncation/strings_strategy.rb#30
  def truncate_strings_proc(threshold); end

  class << self
    # source://rollbar//lib/rollbar/truncation/strings_strategy.rb#11
    def call(payload); end
  end
end

# source://rollbar//lib/rollbar/truncation/strings_strategy.rb#9
Rollbar::Truncation::StringsStrategy::STRING_THRESHOLDS = T.let(T.unsafe(nil), Array)

# source://rollbar//lib/rollbar/util/hash.rb#2
module Rollbar::Util
  class << self
    # source://rollbar//lib/rollbar/util.rb#72
    def clone_obj(obj); end

    # source://rollbar//lib/rollbar/util.rb#129
    def count_method_in_stack(method_symbol, file_path = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#50
    def deep_copy(obj, copied = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#83
    def deep_merge(hash1, hash2, merged = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#123
    def enforce_valid_utf8(payload); end

    # source://rollbar//lib/rollbar/util.rb#9
    def iterate_and_update(obj, block, seen = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#22
    def iterate_and_update_array(array, block, seen); end

    # source://rollbar//lib/rollbar/util.rb#32
    def iterate_and_update_hash(obj, block, seen); end

    # source://rollbar//lib/rollbar/util.rb#5
    def iterate_and_update_with_block(obj, &block); end

    # source://rollbar//lib/rollbar/util.rb#133
    def method_in_stack(method_symbol, file_path = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#137
    def method_in_stack_twice(method_symbol, file_path = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util.rb#99
    def perform_deep_merge(hash1, hash2, merged); end

    # source://rollbar//lib/rollbar/util.rb#111
    def truncate(str, length); end

    # source://rollbar//lib/rollbar/util.rb#119
    def uuid_rollbar_url(data, configuration); end
  end
end

# source://rollbar//lib/rollbar/util/hash.rb#3
module Rollbar::Util::Hash
  class << self
    # source://rollbar//lib/rollbar/util/hash.rb#4
    def deep_stringify_keys(hash, seen = T.unsafe(nil)); end

    # source://rollbar//lib/rollbar/util/hash.rb#18
    def map_value(thing, meth, seen); end

    # source://rollbar//lib/rollbar/util/hash.rb#35
    def replace_seen_children(thing, seen); end
  end
end

# source://rollbar//lib/rollbar/version.rb#2
Rollbar::VERSION = T.let(T.unsafe(nil), String)

# source://rollbar//lib/rollbar/plugins/error_context.rb#1
module RollbarErrorContext
  # Returns the value of attribute rollbar_context.
  #
  # source://rollbar//lib/rollbar/plugins/error_context.rb#2
  def rollbar_context; end

  # Sets the attribute rollbar_context
  #
  # @param value the value to set the attribute rollbar_context to.
  #
  # source://rollbar//lib/rollbar/plugins/error_context.rb#2
  def rollbar_context=(_arg0); end
end

class StandardError < ::Exception
  include ::RollbarErrorContext
end
