env:
  browser: true
  es2021: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
  - prettier
  - prettier/vue
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {}
