AllCops:
  Exclude:
    - 'Gemfile'
    
Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15

Style/ConditionalAssignment:
  Enabled: false
Style/NumericLiterals:
  Enabled: false