AllCops:
  Exclude:
    - 'Gemfile'
    - vendor/**/*.rb
  TargetRubyVersion:
    '2.7.2'
  NewCops: enable
    
Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/**'
    - 'db/**'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_examples', 'shared_context', 'scenario']
  Exclude:
    - 'config/**'
    - 'db/**'
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'config/**'
    - 'db/**'

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

