AllCops:
  Exclude:
    - 'Gemfile'
  TargetRubyVersion:
    '2.4.1'
    
Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

