AllCops:
  Exclude:
    - Gemfile
    - bin/**/*
    - config/**
    - db/**
    # https://github.com/rubocop/rubocop/issues/9832
    - vendor/bundle/**/*
  TargetRubyVersion:
    '2.7.2'
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 100
  Exclude:
    - config/**/*
    - db/**/*

Metrics/AbcSize:
  Exclude:
    - app/controllers/**/*
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - spec/**/*
Metrics/ClassLength:
  Exclude:
    - app/controllers/**/*
Metrics/MethodLength:
  Max: 15
  Exclude:
    - app/controllers/**/*
    - config/**/*
    - db/**/*

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

