AllCops:
  Exclude:
    - 'Gemfile'
  TargetRubyVersion:
    '2.7.2'
    
Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'shared_examples', 'shared_context', 'scenario']
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

