AllCops:
  Exclude:
    - Gemfile
    - bin/**/*
    - config/**
    - db/**
    # https://github.com/rubocop/rubocop/issues/9832
    - vendor/bundle/**/*
  TargetRubyVersion:
    '2.7.2'
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - config/**/*
    - db/**/*

Metrics/AbcSize:
  Max: 25
  Exclude:
    - app/controllers/**/*
    - app/services/**/*
    - spec/**/*
    - lib/**/*
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - spec/**/*
Metrics/ClassLength:
  Max: 350
  Exclude:
    - app/controllers/**/*
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 40
  Exclude:
    - app/controllers/**/*
    - config/**/*
    - db/**/*
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: false
Metrics/PerceivedComplexity:
  Max: 12

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

