# Auditions Configuration for 2027
# This file contains all year-specific configuration for the auditions processing system
# Copy from previous year and update as needed

date_range:
  start: "2026-08-14T12:00:00Z"
  end: "2026-11-01T12:30:00Z"

products:
  packets:
    "Cap City 2027 Battery Audition Packet": "Battery Packet"
    "Cap City 2027 Cymbal Audition Packet": "Cymbal Packet"
    "Cap City 2027 Front Ensemble Audition Packet": "Front Ensemble Packet"
    "Cap City 2027 Visual Ensemble Audition Packet": "Visual Ensemble Packet"

  registrations:
    "CC27 Music Ensemble Audition Registration": "Music Registration"
    "CC27 Visual Ensemble Audition Registration": "Visual Registration"

field_mappings:
  packet:
    name_field: "Name"
    city_field: "City"
    state_field: "State"
    instrument_field: "Instrument"

  registration:
    first_name_field: "First Name"
    last_name_field: "Last Name"
    city_field: "City"
    state_field: "State"
    pronouns_field: "Preferred Pronouns"
    shoe_size_field: "Shoe Size"
    shirt_size_field: "Shirt Size"
    instrument_field: "Primary Instrument"
    birthdate_field: "Birthdate"
    experience_field: "Experience"
    conflicts_field: "Known Conflicts"